# Generated by Django 6.0.6 on 2026-06-25 20:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_shadowing_items(apps, schema_editor):
    ShadowingItem = apps.get_model("tutor", "ShadowingItem")
    defaults = [
        (
            "Scientists are studying how bacteria adapt to new environments.",
            "دانشمندان در حال مطالعه‌اند که باکتری‌ها چگونه به محیط‌های جدید سازگار می‌شوند.",
        ),
        (
            "The university requires a minimum score on the English proficiency test.",
            "دانشگاه حداقل نمره‌ای در آزمون مهارت انگلیسی می‌خواهد.",
        ),
        (
            "Regular practice helps learners improve their pronunciation and fluency.",
            "تمرین منظم به زبان‌آموزان کمک می‌کند تلفظ و روانی‌شان بهتر شود.",
        ),
        (
            "The research findings were published in a peer-reviewed journal.",
            "یافته‌های پژوهش در یک مجله داورى‌شده منتشر شد.",
        ),
        (
            "Students should summarize the main idea in their own words.",
            "دانش‌آموزان باید ایده اصلی را با کلمات خودشان خلاصه کنند.",
        ),
    ]
    for index, (target_text, persian_meaning) in enumerate(defaults):
        ShadowingItem.objects.get_or_create(
            target_text=target_text,
            defaults={
                "persian_meaning": persian_meaning,
                "sort_order": index + 1,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0008_update_speaking_pronunciation_prompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.TextField()),
                ('persian_meaning', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shadowing_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShadowingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField()),
                ('similarity_score', models.PositiveSmallIntegerField(default=0)),
                ('missing_words', models.JSONField(default=list)),
                ('extra_words', models.JSONField(default=list)),
                ('changed_words', models.JSONField(default=list)),
                ('feedback', models.TextField(blank=True)),
                ('persian_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tutor.shadowingitem')),
            ],
        ),
        migrations.RunPython(seed_shadowing_items, migrations.RunPython.noop),
    ]
