# Generated by Django 6.0.6 on 2026-06-25 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0009_shadowing_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularySeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=200)),
                ('lemma', models.CharField(blank=True, max_length=200)),
                ('part_of_speech', models.CharField(blank=True, max_length=50)),
                ('cefr_level', models.CharField(blank=True, max_length=10)),
                ('category', models.CharField(blank=True, max_length=80)),
                ('definition', models.TextField(blank=True)),
                ('persian_meaning', models.TextField(blank=True)),
                ('example', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=200)),
                ('frequency_rank', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['frequency_rank', 'word'],
                'indexes': [models.Index(fields=['cefr_level'], name='tutor_vocab_cefr_le_4c40c0_idx'), models.Index(fields=['category'], name='tutor_vocab_categor_4a27a8_idx'), models.Index(fields=['word'], name='tutor_vocab_word_82e479_idx')],
            },
        ),
    ]
