# Generated by Django 6.0.6 on 2026-06-25 21:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0010_vocabularyseed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='category',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='cefr_level',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddConstraint(
            model_name='vocabularyitem',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='unique_vocab_item_per_user_word'),
        ),
    ]
