# Generated by Django 6.0.6 on 2026-06-25 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0011_vocabularyitem_category_vocabularyitem_cefr_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='collocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='common_mistake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='correction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='shadowing_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularyseed',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vocabularyseed',
            name='collocations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='vocabularyseed',
            name='common_mistake',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularyseed',
            name='correction',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularyseed',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vocabularyseed',
            name='shadowing_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AddIndex(
            model_name='vocabularyseed',
            index=models.Index(fields=['approved'], name='tutor_vocab_approve_df9ab6_idx'),
        ),
        migrations.AddConstraint(
            model_name='vocabularyseed',
            constraint=models.UniqueConstraint(fields=('word', 'category', 'part_of_speech'), name='unique_vocab_seed_word_category_pos'),
        ),
    ]
