# Generated by Django 6.0.6 on 2026-06-30 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def seed_listening_practice_generate_prompts(apps, schema_editor):
    PromptTemplate = apps.get_model("tutor", "PromptTemplate")
    from tutor.prompts.listening_coach import LISTENING_PRACTICE_GENERATE_TEMPLATES

    for template in LISTENING_PRACTICE_GENERATE_TEMPLATES:
        PromptTemplate.objects.update_or_create(
            task_type=template["task_type"],
            provider=template["provider"],
            defaults={
                "title": template["title"],
                "model_name": template["model_name"],
                "system_prompt": template["system_prompt"],
                "temperature": template["temperature"],
                "max_tokens": template["max_tokens"],
                "is_active": template["is_active"],
            },
        )


def unseed_listening_practice_generate_prompts(apps, schema_editor):
    PromptTemplate = apps.get_model("tutor", "PromptTemplate")
    PromptTemplate.objects.filter(task_type="listening_practice_generate").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0031_reading_sessions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListeningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('level', models.CharField(max_length=20)),
                ('stage', models.CharField(blank=True, max_length=40)),
                ('listening_type', models.CharField(blank=True, max_length=40)),
                ('topic', models.CharField(blank=True, max_length=60)),
                ('lesson_focus', models.CharField(blank=True, max_length=60)),
                ('transcript', models.TextField()),
                ('questions_json', models.JSONField(default=list)),
                ('target_vocabulary', models.JSONField(blank=True, default=list)),
                ('shadowing_sentences', models.JSONField(blank=True, default=list)),
                ('estimated_duration_seconds', models.PositiveIntegerField(default=180)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listening_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListeningQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.CharField(max_length=40)),
                ('selected_answer', models.TextField(blank=True)),
                ('correct_answer', models.TextField()),
                ('is_correct', models.BooleanField(default=False)),
                ('question_type', models.CharField(blank=True, max_length=40)),
                ('mistake_category', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='tutor.listeningsession')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RunPython(
            seed_listening_practice_generate_prompts,
            unseed_listening_practice_generate_prompts,
        ),
    ]
