"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
from dotenv import load_dotenv

if os.environ.get("DJANGO_SKIP_DOTENV", "").lower() not in {"1", "true", "yes"}:
    load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

_DEV_SECRET_KEY = "django-insecure-dev-only-change-me-before-production"


def _env_bool(name: str, default: bool) -> bool:
    raw = os.environ.get(name)
    if raw is None:
        return default
    return raw.lower() in ("1", "true", "yes")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool("DJANGO_DEBUG", True)

# SECURITY WARNING: keep the secret key used in production secret!
_secret_from_env = os.environ.get("DJANGO_SECRET_KEY", "").strip()
if not DEBUG and not _secret_from_env:
    raise ImproperlyConfigured("DJANGO_SECRET_KEY is required when DEBUG=false.")
SECRET_KEY = _secret_from_env or _DEV_SECRET_KEY

FRONTEND_URL = os.environ.get("FRONTEND_URL", "http://localhost:5173")
FRONTEND_ORIGIN = os.environ.get("FRONTEND_ORIGIN", FRONTEND_URL)

_DEFAULT_ALLOWED_HOSTS = ["localhost", "127.0.0.1", "0.0.0.0", "192.168.12.228"]
_allowed_hosts_env = os.environ.get("ALLOWED_HOSTS") or os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = list(
    dict.fromkeys(
        _DEFAULT_ALLOWED_HOSTS
        + [
            host.strip()
            for host in _allowed_hosts_env.split(",")
            if host.strip()
        ]
    )
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'tutor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

_extra_cors_origins = [
    origin.strip()
    for origin in os.environ.get("EXTRA_CORS_ORIGINS", "").split(",")
    if origin.strip()
]

CORS_ALLOWED_ORIGINS = list(
    dict.fromkeys(
        [
            "http://localhost:5173",
            "http://127.0.0.1:5173",
            "http://192.168.12.228:5173",
            FRONTEND_ORIGIN,
            *_extra_cors_origins,
        ]
    )
)

CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS.copy()
CORS_ALLOW_CREDENTIALS = True

REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_THROTTLE_RATES": {
        "anon": "60/hour",
        "user": "600/hour",
        "login": "10/minute",
        "ai": "120/hour",
    },
}

# Upload limits
MAX_AUDIO_UPLOAD_BYTES = int(os.environ.get("MAX_AUDIO_UPLOAD_BYTES", str(15 * 1024 * 1024)))
DATA_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("DATA_UPLOAD_MAX_MEMORY_SIZE", str(20 * 1024 * 1024))
)
FILE_UPLOAD_MAX_MEMORY_SIZE = int(
    os.environ.get("FILE_UPLOAD_MAX_MEMORY_SIZE", str(20 * 1024 * 1024))
)

# Learner provider override (developer mode); staff may always override in views.
ALLOW_LEARNER_PROVIDER_OVERRIDE = _env_bool("ALLOW_LEARNER_PROVIDER_OVERRIDE", False)

if not DEBUG:
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# AI provider configuration
DEFAULT_AI_PROVIDER = os.environ.get("DEFAULT_AI_PROVIDER", "ollama")

OLLAMA_HOST = os.environ.get("OLLAMA_HOST", "http://127.0.0.1:11435")
DEFAULT_OLLAMA_MODEL = os.environ.get("DEFAULT_OLLAMA_MODEL", "qwen2.5:7b")
FAST_OLLAMA_MODEL = os.environ.get("FAST_OLLAMA_MODEL", "llama3.2:3b")
EMBEDDING_MODEL = os.environ.get("EMBEDDING_MODEL", "nomic-embed-text")

OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
OPENAI_MODEL = os.environ.get("OPENAI_MODEL", "gpt-5.4-mini")

GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
GEMINI_MODEL = os.environ.get("GEMINI_MODEL", "gemini-3.5-flash")

ANTHROPIC_API_KEY = os.environ.get("ANTHROPIC_API_KEY", "")
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-5")

# Voice (STT / TTS) — swappable providers via env
TRANSCRIPTION_PROVIDER = os.environ.get("TRANSCRIPTION_PROVIDER", "openai_whisper")
TTS_PROVIDER = os.environ.get("TTS_PROVIDER", "browser_tts")
WHISPER_MODEL = os.environ.get("WHISPER_MODEL", "whisper-1")
WHISPER_MODEL_QUALITY = os.environ.get("WHISPER_MODEL_QUALITY", "gpt-4o-transcribe")
WHISPER_MODEL_FAST = os.environ.get("WHISPER_MODEL_FAST", "gpt-4o-mini-transcribe")
SPEAKING_EVAL_MODEL_ADVANCED = os.environ.get("SPEAKING_EVAL_MODEL_ADVANCED", "gpt-4o")
SPEAKING_EVAL_MODEL_STANDARD = os.environ.get("SPEAKING_EVAL_MODEL_STANDARD", "gpt-4o-mini")
WRITING_EVAL_MODEL_ADVANCED = os.environ.get("WRITING_EVAL_MODEL_ADVANCED", "gpt-4o")
WRITING_EVAL_MODEL_STANDARD = os.environ.get("WRITING_EVAL_MODEL_STANDARD", "gpt-4o-mini")
READING_AI_PROVIDER = os.environ.get("READING_AI_PROVIDER", "openai")
READING_GENERATION_MODEL = os.environ.get("READING_GENERATION_MODEL", "gpt-5.5")
READING_FAST_MODEL = os.environ.get("READING_FAST_MODEL", OPENAI_MODEL)
LOCAL_WHISPER_MODEL = os.environ.get("LOCAL_WHISPER_MODEL", "base")
OPENAI_TTS_MODEL = os.environ.get("OPENAI_TTS_MODEL", "tts-1")
OPENAI_TTS_VOICE = os.environ.get("OPENAI_TTS_VOICE", "alloy")

STUDY_PLAN_DEFAULTS = {
    "vocab_count": 5,
    "mistake_count": 3,
    "minutes_per_track": {
        "grammar": 15,
        "reading": 15,
        "writing": 15,
        "listening": 10,
        "speaking": 10,
        "shadowing": 10,
    },
}
