from django.urls import path

from core.views import HealthView
from .auth_views import CSRFView, LoginView, LogoutView, MeView
from .views import (
    AdminPromptDetailView,
    AdminPromptResetView,
    AdminPromptsListView,
    AnalyticsProgressView,
    ChatView,
    DashboardView,
    LessonCompleteView,
    LessonQuizSubmitView,
    LessonQuizView,
    LessonRecommendationView,
    LessonStartRecommendedView,
    LessonTopicsView,
    ListeningGenerateView,
    ListeningPracticeContextView,
    ListeningPracticeGenerateView,
    ListeningPracticeSubmitView,
    ListeningQuizGenerateView,
    ListeningQuizSubmitView,
    MistakesListView,
    OllamaStatusView,
    PlanGenerateView,
    PlanTodayView,
    PromptsListView,
    ReadingAnalyzeView,
    ReadingContextView,
    ReadingGenerateView,
    ReadingQuizGenerateView,
    ReadingQuizSubmitView,
    ReadingSubmitView,
    ReadinessView,
    ShadowingAttemptAudioView,
    ShadowingAttemptView,
    ShadowingFromSentencesView,
    ShadowingItemsListView,
    SpeakingAttemptAudioView,
    ToeflPromptView,
    TranscribeView,
    TTSView,
    VocabAddRandomFromCategoryView,
    VocabCategoriesView,
    VocabCategoryStatsView,
    VocabDueView,
    VocabFromSeedView,
    VocabListCreateView,
    VocabQuizMistakeView,
    VocabReviewView,
    VocabSeedsListView,
    WritingEditView,
    WritingEditGenerateView,
    WritingRevisionCompareView,
    ParaphraseGenerateView,
    ParaphraseCheckView,
)

urlpatterns = [
    path("health/", HealthView.as_view(), name="health"),
    path("auth/me/", MeView.as_view(), name="auth-me"),
    path("auth/login/", LoginView.as_view(), name="auth-login"),
    path("auth/logout/", LogoutView.as_view(), name="auth-logout"),
    path("csrf/", CSRFView.as_view(), name="csrf"),
    path("chat/", ChatView.as_view(), name="chat"),
    path("lesson/recommendation/", LessonRecommendationView.as_view(), name="lesson-recommendation"),
    path("lesson/topics/", LessonTopicsView.as_view(), name="lesson-topics"),
    path(
        "lesson/start-recommended/",
        LessonStartRecommendedView.as_view(),
        name="lesson-start-recommended",
    ),
    path("lesson/complete/", LessonCompleteView.as_view(), name="lesson-complete"),
    path("lesson/quiz/", LessonQuizView.as_view(), name="lesson-quiz"),
    path("lesson/quiz/submit/", LessonQuizSubmitView.as_view(), name="lesson-quiz-submit"),
    path("prompts/", PromptsListView.as_view(), name="prompts"),
    path("admin/prompts/", AdminPromptsListView.as_view(), name="admin-prompts"),
    path(
        "admin/prompts/<int:prompt_id>/",
        AdminPromptDetailView.as_view(),
        name="admin-prompt-detail",
    ),
    path(
        "admin/prompts/<int:prompt_id>/reset/",
        AdminPromptResetView.as_view(),
        name="admin-prompt-reset",
    ),
    path("ollama/status/", OllamaStatusView.as_view(), name="ollama-status"),
    path("mistakes/", MistakesListView.as_view(), name="mistakes"),
    path("mistakes/vocab/", VocabQuizMistakeView.as_view(), name="mistakes-vocab"),
    path("reading/analyze/", ReadingAnalyzeView.as_view(), name="reading-analyze"),
    path("reading/context/", ReadingContextView.as_view(), name="reading-context"),
    path("reading/generate/", ReadingGenerateView.as_view(), name="reading-generate"),
    path("reading/submit/", ReadingSubmitView.as_view(), name="reading-submit"),
    path("reading/quiz/generate/", ReadingQuizGenerateView.as_view(), name="reading-quiz-generate"),
    path("reading/quiz/submit/", ReadingQuizSubmitView.as_view(), name="reading-quiz-submit"),
    path("writing/edit/", WritingEditView.as_view(), name="writing-edit"),
    path(
        "writing/edit/generate/",
        WritingEditGenerateView.as_view(),
        name="writing-edit-generate",
    ),
    path(
        "writing/revision/compare/",
        WritingRevisionCompareView.as_view(),
        name="writing-revision-compare",
    ),
    path(
        "writing/paraphrasing/generate/",
        ParaphraseGenerateView.as_view(),
        name="writing-paraphrase-generate",
    ),
    path(
        "writing/paraphrasing/check/",
        ParaphraseCheckView.as_view(),
        name="writing-paraphrase-check",
    ),
    path("listening/generate/", ListeningGenerateView.as_view(), name="listening-generate"),
    path(
        "listening/quiz/generate/",
        ListeningQuizGenerateView.as_view(),
        name="listening-quiz-generate",
    ),
    path(
        "listening/quiz/submit/",
        ListeningQuizSubmitView.as_view(),
        name="listening-quiz-submit",
    ),
    path(
        "listening/practice/context/",
        ListeningPracticeContextView.as_view(),
        name="listening-practice-context",
    ),
    path(
        "listening/generate-practice/",
        ListeningPracticeGenerateView.as_view(),
        name="listening-generate-practice",
    ),
    path(
        "listening/submit-practice/",
        ListeningPracticeSubmitView.as_view(),
        name="listening-submit-practice",
    ),
    path("transcribe/", TranscribeView.as_view(), name="transcribe"),
    path("speaking/attempt-audio/", SpeakingAttemptAudioView.as_view(), name="speaking-attempt-audio"),
    path("shadowing/items/from-sentences/", ShadowingFromSentencesView.as_view(), name="shadowing-from-sentences"),
    path("shadowing/items/", ShadowingItemsListView.as_view(), name="shadowing-items"),
    path(
        "shadowing/items/<int:item_id>/attempt/",
        ShadowingAttemptView.as_view(),
        name="shadowing-attempt",
    ),
    path(
        "shadowing/items/<int:item_id>/attempt-audio/",
        ShadowingAttemptAudioView.as_view(),
        name="shadowing-attempt-audio",
    ),
    path("tts/", TTSView.as_view(), name="tts"),
    path("toefl/prompt/", ToeflPromptView.as_view(), name="toefl-prompt"),
    path("vocab/", VocabListCreateView.as_view(), name="vocab"),
    path("vocab/seeds/", VocabSeedsListView.as_view(), name="vocab-seeds"),
    path("vocab/categories/", VocabCategoriesView.as_view(), name="vocab-categories"),
    path("vocab/category-stats/", VocabCategoryStatsView.as_view(), name="vocab-category-stats"),
    path(
        "vocab/add-random-from-category/",
        VocabAddRandomFromCategoryView.as_view(),
        name="vocab-add-random",
    ),
    path("vocab/due/", VocabDueView.as_view(), name="vocab-due"),
    path(
        "vocab/from-seed/<int:seed_id>/",
        VocabFromSeedView.as_view(),
        name="vocab-from-seed",
    ),
    path("vocab/<int:item_id>/review/", VocabReviewView.as_view(), name="vocab-review"),
    path("plan/today/", PlanTodayView.as_view(), name="plan-today"),
    path("plan/today/generate/", PlanGenerateView.as_view(), name="plan-generate"),
    path("dashboard/", DashboardView.as_view(), name="dashboard"),
    path("readiness/", ReadinessView.as_view(), name="readiness"),
    path("analytics/progress/", AnalyticsProgressView.as_view(), name="analytics-progress"),
]
